- hosts: reachable
  serial:
    - 1
    - "50%"
    - "75%"
    - "100%"
  become: yes
  become_method: sudo
  gather_facts: true
  ignore_errors: false
  ignore_unreachable: true
  vars:
    headscale_version: '0.22.3'
    headscale_arch: 'arm64'
  roles:
    - role: headscale
  post_tasks:
    - meta: clear_host_errors
      when: ignore_unreachable